# Created by trellis-cli v0.3.1
# Documentation: https://roots.io/trellis/docs/wordpress-sites/

wordpress_sites:
  skinnartrampet.se:
    site_hosts:
    - canonical: skinnartrampet.test
      redirects:
      - www.skinnartrampet.test
    local_path: ../site
    admin_email: eric@adpine.se
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
