# Created by trellis-cli v0.3.1
# Documentation: https://roots.io/trellis/docs/wordpress-sites/

wordpress_sites:
  skinnartrampet.se:
    site_hosts:
    - canonical: staging.skinnartrampet.se
      redirects:
      - www.staging.skinnartrampet.se
    local_path: ../site
    branch: master
    repo: git@github.com:erickarlsso/skinnartrampet.se.git
    repo_subtree_path: site
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: false
